language: node_js

sudo: required

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'
  - "iojs"

before_script:
  - npm install -g johnny-five
  - npm install -g dnode
  - npm install -g nodebot-workshop
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes g++-4.8
  - export CXX="g++-4.8"

script:
  - nodebot-workshop
